version: '3.3'

services:
  api:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: postgres:11.3
    restart: always
    environment:
      - PGHOST=localhost
      - PGUSER=postgres
    volumes:
      - db_postgres:/var/lib/postgresql/data

volumes:
  db_postgres:
